# Generated by Django 6.0 on 2025-12-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('leader_full_name', models.CharField(max_length=200)),
                ('leader_phone', models.CharField(max_length=32)),
                ('leader_whatsapp', models.CharField(max_length=32)),
                ('leader_email', models.EmailField(max_length=254)),
                ('leader_gender', models.CharField(max_length=16)),
                ('leader_age', models.PositiveIntegerField()),
                ('leader_nationality', models.CharField(max_length=80)),
                ('leader_resident_country', models.CharField(max_length=80)),
                ('leader_identity_type', models.CharField(max_length=16)),
                ('leader_identity_last4', models.CharField(max_length=8)),
                ('entry_type_for_egypt', models.CharField(blank=True, default='', max_length=16)),
                ('origin_city', models.CharField(max_length=80)),
                ('destination_city', models.CharField(max_length=80)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField()),
                ('adults_count', models.PositiveIntegerField(default=1)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('pax_total', models.PositiveIntegerField(default=1)),
                ('companions_mode', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('couples_answer', models.CharField(max_length=8)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('docs_acknowledged', models.BooleanField(default=False)),
                ('travelers', models.JSONField(blank=True, default=list)),
                ('children_details', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
