# Generated by Django 6.0 on 2025-12-20 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trip_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='next_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='source',
            field=models.CharField(blank=True, default='WEB', max_length=50),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('QUOTED', 'Quoted'), ('BOOKED', 'Booked'), ('CLOSED_WON', 'Closed (Won)'), ('CLOSED_LOST', 'Closed (Lost)')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='trip_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='TripRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NOTE', 'Note'), ('WHATSAPP', 'WhatsApp'), ('CALL', 'Call'), ('EMAIL', 'Email')], default='NOTE', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_request_notes', to=settings.AUTH_USER_MODEL)),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='trip_requests.triprequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
