# Generated by Django 6.0 on 2025-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_requests', '0002_triprequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='resident_country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
