# Generated by Django 6.0 on 2025-12-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_requests', '0003_triprequest_nationality_triprequest_resident_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='trip_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='trip_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
