# Generated by Django 6.0 on 2026-01-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_requests', '0004_triprequest_trip_slug_triprequest_trip_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='trip_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
