# Generated by Django 6.0 on 2026-01-04 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_requests', '0005_alter_triprequest_trip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_public_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='triprequestnote',
            options={},
        ),
        migrations.AddField(
            model_name='triprequest',
            name='destination_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='group_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='internal_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='internal_code_override',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='lead_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='lead_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='origin_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='reservation_code_override',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='reservation_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='traveler_seq',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='trip_public_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='couples_answer',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='depart_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='destination_city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='entry_type_for_egypt',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_full_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_gender',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_identity_last4',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_identity_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_nationality',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_resident_country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_whatsapp',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='origin_city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('URGENT', 'URGENT')], db_index=True, default='MEDIUM', max_length=16),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CONTACTED', 'CONTACTED'), ('QUALIFIED', 'QUALIFIED'), ('QUOTED', 'QUOTED'), ('BOOKED', 'BOOKED'), ('CLOSED_WON', 'CLOSED (WON)'), ('CLOSED_LOST', 'CLOSED (LOST)')], db_index=True, default='NEW', max_length=16),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='trip_code',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triprequestnote',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='triprequestnote',
            name='kind',
            field=models.CharField(blank=True, default='NOTE', max_length=32),
        ),
        migrations.AlterField(
            model_name='triprequestnote',
            name='trip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='trip_requests.triprequest'),
        ),
    ]
