# Generated by Django 6.0 on 2026-01-04 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_requests', '0006_reservationsequence_alter_triprequestnote_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='triprequestnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='reservationsequence',
            old_name='last_seq',
            new_name='last_r',
        ),
        migrations.RenameField(
            model_name='triprequest',
            old_name='reservation_seq',
            new_name='reservation_r',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='destination_code',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='internal_code',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='lead_code',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='origin_code',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='reservation_code_override',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='traveler_seq',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='is_leader',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='traveler_p',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservationsequence',
            name='trip_public_code',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='couples_answer',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='depart_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='destination_city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='entry_type_for_egypt',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='internal_code_override',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_gender',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_identity_last4',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_identity_type',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_nationality',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_phone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_resident_country',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_whatsapp',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='origin_city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='source',
            field=models.CharField(blank=True, default='WEB', max_length=50),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('QUOTED', 'Quoted'), ('BOOKED', 'Booked'), ('CLOSED_WON', 'Closed (Won)'), ('CLOSED_LOST', 'Closed (Lost)')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='trip_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='trip_public_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='triprequestnote',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='triprequestnote',
            name='kind',
            field=models.CharField(choices=[('NOTE', 'Note'), ('WHATSAPP', 'WhatsApp'), ('CALL', 'Call'), ('EMAIL', 'Email')], default='NOTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='triprequestnote',
            name='trip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='trip_requests.triprequest'),
        ),
    ]
