# Generated by Django 6.0 on 2026-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_requests', '0007_alter_triprequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationsequence',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='lead_seq',
        ),
        migrations.AlterField(
            model_name='reservationsequence',
            name='trip_public_code',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='couples_answer',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='depart_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='destination_city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='internal_code_override',
            field=models.CharField(blank=True, default='', max_length=96),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='is_leader',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_gender',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_identity_last4',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_identity_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_nationality',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_resident_country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='leader_whatsapp',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='origin_city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='traveler_p',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='trip_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=96, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='trip_public_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
