# Generated by Django 6.0 on 2026-04-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_requests', '0008_remove_reservationsequence_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('gender', models.CharField(blank=True, default='', max_length=16)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=80)),
                ('resident_country', models.CharField(blank=True, default='', max_length=80)),
                ('identity_type', models.CharField(blank=True, default='', max_length=16)),
                ('identity_last4', models.CharField(blank=True, default='', max_length=8)),
                ('identity_hash', models.CharField(blank=True, default='', help_text='Hashed identity for data masking', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_age',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_email',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_full_name',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_gender',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_identity_last4',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_identity_type',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_nationality',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_phone',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_resident_country',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='leader_whatsapp',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='resident_country',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_requests', to='trip_requests.customer'),
        ),
    ]
