# Generated by Django 6.0 on 2025-12-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyCustomTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('priceFrom', models.PositiveIntegerField(blank=True, null=True)),
                ('priceTo', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='EGP', max_length=8)),
                ('durationNights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
