# Generated by Django 6.0 on 2025-12-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dest_code',
            field=models.CharField(blank=True, default='', help_text='For STAY: e.g. SIWA, DHB, SHM', max_length=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='from_code',
            field=models.CharField(blank=True, default='', help_text='For DAYUSE origin: e.g. CAI, MNS', max_length=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='global_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Global sequence number for the company (auto = id).', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='internal_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Company-only key: STAY uses dest_code, DAYUSE uses FROM-TO', max_length=32),
        ),
        migrations.AddField(
            model_name='trip',
            name='internal_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Company-only sequence per internal_key (auto). Not shown to customers.', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='public_code',
            field=models.CharField(blank=True, db_index=True, help_text='Public unique code used by frontend as slug e.g. ST-0000007-SIWA or DU-0000008-CAI-ALEX', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='to_code',
            field=models.CharField(blank=True, default='', help_text='For DAYUSE destination: e.g. ALEX, AIN', max_length=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
