# Generated by Django 6.0 on 2025-12-31 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_dest_code_trip_from_code_trip_global_seq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique destination code e.g. SIWA, DHB, ALEX, AIN', max_length=12, unique=True)),
                ('slug', models.SlugField(help_text='SEO slug e.g. siwa, dahab, alexandria', max_length=120, unique=True)),
                ('name', models.CharField(help_text='Display name e.g. Siwa', max_length=120)),
                ('country', models.CharField(blank=True, default='Egypt', max_length=80)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('gallery_urls', models.JSONField(blank=True, default=list)),
                ('video_urls', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='EGP', max_length=8)),
                ('duration_label', models.CharField(blank=True, default='', max_length=64)),
                ('options', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.destination')),
            ],
            options={
                'indexes': [models.Index(fields=['destination', 'is_active', 'sort_order'], name='trips_activ_destina_53a043_idx')],
                'unique_together': {('destination', 'slug')},
            },
        ),
    ]
