# Generated by Django 6.0 on 2026-01-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_destination_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='media',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='social_proof',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
