# Generated by Django 6.0 on 2026-01-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_media_trip_social_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='global_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Global sequence number (auto = id).', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='internal_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Company-only sequence per internal_key (auto).', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='public_code',
            field=models.CharField(blank=True, db_index=True, help_text='Public code e.g. ST-0000007-SIWA or DU-0000008-CAI-ALEX', max_length=32, null=True, unique=True),
        ),
    ]
